{
 "title": "Attempt 1",
 "description": "AirGradient influxdb data to dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "description": "carbon dioxde levels should be under 1000",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"rco2\" as \"Bedroom1\", to_timestamp(time) as \"time\" FROM \"air\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "in Fahrenheit",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", (1.8 * atmp)+32 as \"Bedroom1\" FROM \"air\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "Particle Matter 2.5",
   "type": "timeseries",
   "description": "pm02; should be 5 or below",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"pm02\" as \"Bedroom1\", \"time\" FROM \"air\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", rhum as \"Bedroom1\" FROM \"air\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "Bedroom 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"pm01\", \"pm02\", \"pm10\" FROM \"air\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "timeseries",
   "description": "Total Volatile Organic Compounds",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"tvoc_index\" as \"Bedroom1\", to_timestamp(time) as \"time\" FROM \"air\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"time\" DESC "
    }
   ]
  }
 ]
}